### ISSUE TITLE
Unabel to run menu/init

### ISSUE THREAD

**Issue by neoacevedo** [wdmg/yii2-menu#2]
I get the following error: 
> yii\base\InvalidRouteException: Unable to resolve the request "menu/init". in /app/vendor/yiisoft/yii2/base/Module.php:543

**Comment by alex-wdmg** [comment]
Does not find the path because the application does not know anything about the existence of this module.

The module must be added and activated on the [Butterfly.CMS](https://github.com/wdmg/butterfly.cms). Or if you use the module standalone you need to init it in bootstrap of app config:

  `
    $config['modules']['menu'] = [
              'class' => 'wdmg\yii2-menu\Module',
    ];
`
